export const GET_CURRENT_COUNTRY = "GET_CURRENT_COUNTRY";
export const SET_CURRENT_COUNTRY = "SET_CURRENT_COUNTRY";
export const SET_COUNTRY = "SET_COUNTRY";

export const  GET_CURRENT_USER_REQUEST = "GET_CURRENT_USER_REQUEST";
export const  GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS";
export const  GET_CURRENT_USER_FAIL = "GET_CURRENT_USER_FAIL";

export const SIGN_UP = "SIGN_UP"
export const LOGIN = "LOGIN"
export const LOGGEDIN = "LOGGEDIN"
export const LOG_OUT = "LOG_OUT"
export const FORGOT_PASSWORD = "FORGOT_PASSWORD"
export const REMOVE_USER = "REMOVE_USER"